# rose-pine-primeagen.toml

inherits = "rose-pine"

"ui.background" = "black"  # pitch black
"ui.selection" = "#2a273f"
"ui.cursor" = "#ebbcba"
"ui.cursor.primary" = "#ebbcba"

"comment" = "#6e6a86"
"constant" = "#9ccfd8"
"string" = "#f6c177"
"keyword" = "#c4a7e7"
"function" = "#ebbcba"
"type" = "#9ccfd8"
"constructor" = "#ea9a97"
"label" = "#f6c177"
"operator" = "#c4a7e7"
"variable" = "#e0def4"
"attribute" = "#f6c177"
"namespace" = "#c4a7e7"
"special" = "#eb6f92"

